id: P000696
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:36.096481
source_metadata:
  id: bdr:W1PD159416
  title: བོད་ཀྱི་རྩོམ་རིག་སྐོར་གྱི་མནོ་བསམ།
  author: ''
  volumes:
    01b1222789854aef8b5a7ed407dcf869:
      image_group_id: I2PD18983
      title: ''
      volume_number: 1
      total_pages: 448
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
