id: P000696
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159416
  title: བོད་ཀྱི་རྩོམ་རིག་སྐོར་གྱི་མནོ་བསམ།
  author: ''
  volumes:
    01b1222789854aef8b5a7ed407dcf869:
      image_group_id: I2PD18983
      title: ''
      volume_number: 1
      total_pages: 448
