id: IA9B4E333
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:29:25+00:00'
last_modified: '2022-06-07T12:41:13.787002+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159416
  title: བོད་ཀྱི་རྩོམ་རིག་སྐོར་གྱི་མནོ་བསམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A659:
      image_group_id: I2PD18983
      title: ''
      total_pages: 448
      order: 1
      base_file: A659.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
